/* GENERATED by tools/pack_assets.py — do not edit by hand. */
#ifndef THEDEMO_ASSETS_H
#define THEDEMO_ASSETS_H
#include <stdint.h>

/* title_bg: 8bpp 320x240 76800 bytes + 512 B palette */
extern const uint8_t  asset_title_bg_data[];
extern const uint8_t  asset_title_bg_end[];
#define ASSET_TITLE_BG_W 320
#define ASSET_TITLE_BG_H 240
#define ASSET_TITLE_BG_SIZE 76800
extern const uint16_t asset_title_bg_pal[256];

/* greetz_bg: 8bpp 320x240 76800 bytes + 512 B palette */
extern const uint8_t  asset_greetz_bg_data[];
extern const uint8_t  asset_greetz_bg_end[];
#define ASSET_GREETZ_BG_W 320
#define ASSET_GREETZ_BG_H 240
#define ASSET_GREETZ_BG_SIZE 76800
extern const uint16_t asset_greetz_bg_pal[256];

/* endcard_bg: 8bpp 320x240 76800 bytes + 512 B palette */
extern const uint8_t  asset_endcard_bg_data[];
extern const uint8_t  asset_endcard_bg_end[];
#define ASSET_ENDCARD_BG_W 320
#define ASSET_ENDCARD_BG_H 240
#define ASSET_ENDCARD_BG_SIZE 76800
extern const uint16_t asset_endcard_bg_pal[256];

#endif
