/* Generated by tools/pack_assets.py from round6. Do not edit.
 * Flash only, no decompression, no SRAM copy. */
#ifndef COLOSSUS_PAINTED_ASSETS_H
#define COLOSSUS_PAINTED_ASSETS_H
#include <stdint.h>
extern const uint8_t wordmark_pixels[10240];
extern const uint16_t wordmark_palette[16];
extern const uint8_t dusk_matcap_pixels[4096];
extern const uint16_t dusk_matcap_palette[256];
extern const uint8_t dusk_sky_pixels[16384];
extern const uint16_t dusk_sky_palette[256];
extern const uint8_t bronze_wear_pixels[4096];
extern const uint16_t bronze_wear_palette[256];
extern const uint8_t stone_pixels[4096];
extern const uint16_t stone_palette[256];
extern const uint8_t dawn_sky_pixels[16384];
extern const uint16_t dawn_sky_palette[256];
extern const uint8_t dawn_matcap_pixels[4096];
extern const uint16_t dawn_matcap_palette[256];
extern const uint8_t warm_environment_pixels[4096];
extern const uint16_t warm_environment_palette[256];
extern const uint8_t furnace_pixels[2048];
extern const uint16_t furnace_palette[256];
extern const uint8_t ember_stamps_pixels[512];
extern const uint16_t ember_stamps_palette[16];
extern const uint8_t end_inscription_pixels[5120];
extern const uint16_t end_inscription_palette[16];
extern const uint8_t tendon_brushed_metal_pixels[512];
extern const uint16_t tendon_brushed_metal_palette[16];
#endif
