"""Phase: shared proportions, flat review plates, and C layout. No smoothing."""
from PIL import Image, ImageDraw
from pathlib import Path
import json, math
ROOT=Path(__file__).resolve().parents[2]
params=json.loads((ROOT/'colossus/assets/body_parameters.json').read_text())
parts=[]
def box(name,x,y,w,h,d=.6,group=0,mat=1,z=0,turn=0):
    parts.append(dict(name=name,x=x,y=y,z=z,w=w,h=h,d=d,group=group,mat=mat,turn=turn))
# World units: sole 0, crown 20.4. All dimensions are full extents.
for s in [-1,1]:
    box('planted_foot',s*1.6,.65,2.7 if s==-1 else 2.3,1.3,3.1 if s==-1 else 2.4,z=params['near_foot_forward'] if s==-1 else .3,turn=params['near_foot_turn_degrees'] if s==-1 else 0)
    box('short_leg',s*1.4,3.1,1.35,3.6,2.1)
box('pelvis',0,5.4,3.5,1.3,2.8)
for s in [-1,1]:
    box('torso_rib',s*(params['torso_width']-.8)/2,10.4,.8,8.8,params['torso_depth'])
    for y in [7.2,9.4,13.8]:
        if not(s==1 and y==9.4): box('cross_rib',s*.65,y,1.3,.55,.7,z=-1.9)
box('sternum_tendon',0,10.6,.36,8.4,.5,mat=2,z=.35)
for s in [-1,1]:
    g=1 if s==-1 else 2
    y=params['high_shoulder']-(params['shoulder_drop'] if s==-1 else 0)
    box('shoulder',s*2.75,y,2.6,2.1,3.0,g)
    box('upper_arm',s*3.75,y-2,1.3,3,1.8,g)
    box('forearm_outer',s*4.95,y-4.6,1.15,3.9,2.2,g)
    box('forearm_inner',s*3.4,y-4.6,.95,3.9,2.2,g)
    box('forearm_tendon',s*4.2,y-4.6,.45,3.9,.65,g,2,z=-.7)
    hg=3 if s==-1 else 4
    box('palm',s*4.4,y-7,3.8,1.55,1.35,hg)
    for i,xx in enumerate([4.4-params['hand_finger_pitch'],4.4,4.4+params['hand_finger_pitch']]):
        yy=y-8.85+(i==2)*.35
        box('finger_rib_a',s*(xx-.3),yy,.38,params['hand_finger_length'],.85,hg)
        box('finger_rib_b',s*(xx+.3),yy,.38,params['hand_finger_length'],.85,hg)
        box('finger_tendon',s*xx,yy,.18,2.25,.45,hg,2,z=-.15)
    box('opposed_thumb',s*1.85,y-7.35,.7,1.9,1.0,hg)
box('neck',0,16.05,1.8,1.6,1.5)
box('eye_recess',0,17.3,1.8,2.35,.3,mat=0,z=.45)
for s in [-1,1]: box('hood',s*1.25,17.5,.7,2.7,1.6)
box('hood_brow',0,18.45,3.0,.85,2.7,z=-.55)
box('crown_left',-1.05,19.5,1.15,1.8,1.2)
box('crown_right',.95,19.15,1.05,1.1,1.2)
(ROOT/'colossus/assets/body_layout.json').write_text(json.dumps(parts,indent=2)+'\n')
with (ROOT/'colossus/body_layout.h').open('w') as f:
    f.write('/* Generated by assets/silhouette.py; dimensions shared with review plates. */\nstatic const BodyPart body_parts[] = {\n')
    for p in parts:
        f.write(' {%s}, /* %s */\n'%(','.join(str(p[k]) for k in ['x','y','z','w','h','d','turn','group','mat']),p['name']))
    f.write('};\n')
    f.write('#define BODY_SHOULDER_DROP '+str(params['shoulder_drop'])+'f\n')
    f.write('#define BODY_NEAR_WRIST_Y '+str(params['high_shoulder']-params['shoulder_drop']-7)+'f\n')
    f.write('#define BODY_FAR_WRIST_Y '+str(params['high_shoulder']-7)+'f\n')
bg='#8098a8'; ink='#101820'
def plate(name,center,scale,filterpart=lambda p:True,size=(320,240)):
    im=Image.new('RGB',size,bg); d=ImageDraw.Draw(im)
    def xy(x,y):return (round(size[0]/2+(x-center[0])*scale),round(size[1]/2-(y-center[1])*scale))
    for p in parts:
        if filterpart(p):
            a=xy(p['x']-p['w']/2,p['y']+p['h']/2); b=xy(p['x']+p['w']/2,p['y']-p['h']/2)
            
            if p['turn']:
                skew=round(math.sin(math.radians(p['turn']))*p['d']*scale*.4)
                d.polygon([(a[0]+skew,a[1]),(b[0]+skew,a[1]),(b[0]-skew,b[1]),(a[0]-skew,b[1])],fill=ink)
            else:d.rectangle((*a,*b),fill=ink)
    if name=='eye':
        d.polygon([xy(-1.4,18.15),xy(1.4,18.15),xy(1.1,16.3),xy(-1.1,16.3)],fill=ink)
    if name in ['whole','eye']:
        pts=[xy(math.cos(t*math.pi/24)*.78,17.4+math.sin(t*math.pi/24)*.78) for t in range(48)]
        d.polygon(pts,fill=bg if name=='eye' else ink)
        pts=[xy(math.cos(t*math.pi/24)*.48,17.4+math.sin(t*math.pi/24)*.48) for t in range(48)]
        d.polygon(pts,fill=ink if name=='eye' else bg)
        if name=='eye':d.rectangle((*xy(-1.4,18.3),*xy(1.4,17.95)),fill=ink)
    return im
plates={'whole':plate('whole',(0,10.2),8.5),'hand':plate('hand',(-4.1,4.9),33,lambda p:p['group'] in [1,3]),'eye':plate('eye',(0,17.45),68,lambda p:p['y']>16 and p['y']<19),'crown':plate('crown',(0,18.65),66,lambda p:p['y']>16)}
for name,im in plates.items():
    im.save(ROOT/f'briefs/sketches/silhouette-{name}.png')
    im.resize((960,720),Image.Resampling.NEAREST).save(ROOT/f'briefs/sketches/silhouette-{name}-3x.png')
sheet=Image.new('RGB',(320,240),bg)
sheet.paste(plates['whole'].crop((90,0,230,240)),(0,0))
for i,name in enumerate(['hand','eye','crown']):
    # Render each detail directly at panel size, never resample the pixels.
    cent,sc,filt=[((-4.1,4.9),12,lambda p:p['group'] in [1,3]),((0,17.45),23,lambda p:16<p['y']<19),((0,18.65),23,lambda p:p['y']>16)][i]
    sheet.paste(plate(name,cent,sc,filt,(174,76)),(146,i*80))
sheet.save(ROOT/'briefs/sketches/silhouette-contact.png')
sheet.resize((960,720),Image.Resampling.NEAREST).save(ROOT/'briefs/sketches/silhouette-contact-3x.png')
