/* GENERATED by tools/pack_assets.py — do not edit by hand. */
#ifndef THEDEMO_ASSETS_H
#define THEDEMO_ASSETS_H
#include <stdint.h>

/* title_bg: 8bpp 320x240 76800 bytes + 512 B palette */
extern const uint8_t  asset_title_bg_data[];
extern const uint8_t  asset_title_bg_end[];
#define ASSET_TITLE_BG_W 320
#define ASSET_TITLE_BG_H 240
#define ASSET_TITLE_BG_SIZE 76800
extern const uint16_t asset_title_bg_pal[256];

/* star_pano: rgb565 256x128 65536 bytes */
extern const uint8_t  asset_star_pano_data[];
extern const uint8_t  asset_star_pano_end[];
#define ASSET_STAR_PANO_W 256
#define ASSET_STAR_PANO_H 128
#define ASSET_STAR_PANO_SIZE 65536

/* disk_tex: rgb565 256x256 131072 bytes */
extern const uint8_t  asset_disk_tex_data[];
extern const uint8_t  asset_disk_tex_end[];
#define ASSET_DISK_TEX_W 256
#define ASSET_DISK_TEX_H 256
#define ASSET_DISK_TEX_SIZE 131072

/* solar0: rgb565 128x128 32768 bytes */
extern const uint8_t  asset_solar0_data[];
extern const uint8_t  asset_solar0_end[];
#define ASSET_SOLAR0_W 128
#define ASSET_SOLAR0_H 128
#define ASSET_SOLAR0_SIZE 32768

/* solar1: rgb565 128x128 32768 bytes */
extern const uint8_t  asset_solar1_data[];
extern const uint8_t  asset_solar1_end[];
#define ASSET_SOLAR1_W 128
#define ASSET_SOLAR1_H 128
#define ASSET_SOLAR1_SIZE 32768

/* solar2: rgb565 128x128 32768 bytes */
extern const uint8_t  asset_solar2_data[];
extern const uint8_t  asset_solar2_end[];
#define ASSET_SOLAR2_W 128
#define ASSET_SOLAR2_H 128
#define ASSET_SOLAR2_SIZE 32768

/* endcard_bg: 8bpp 320x240 76800 bytes + 512 B palette */
extern const uint8_t  asset_endcard_bg_data[];
extern const uint8_t  asset_endcard_bg_end[];
#define ASSET_ENDCARD_BG_W 320
#define ASSET_ENDCARD_BG_H 240
#define ASSET_ENDCARD_BG_SIZE 76800
extern const uint16_t asset_endcard_bg_pal[256];

#endif
