/* GENERATED by tools/make_lens_lut.py — do not edit by hand.
 * Gravitational-lensing remap LUT for the SINGULARITY climax. */
#ifndef SINGULARITY_LENS_LUT_H
#define SINGULARITY_LENS_LUT_H
#include <stdint.h>

#define LENS_LUT_W      320
#define LENS_LUT_H      240
#define LENS_PANO_W     256
#define LENS_PANO_H     128
#define LENS_SHADOW     0xFFFFu

/* 320*240 uint16: 0xFFFF == event-horizon shadow, else (u<<7)|v
 * into the 256x128 equirectangular star panorama. */
extern const uint16_t lens_lut[LENS_LUT_W * LENS_LUT_H];

#endif
