"""Compile the single distant painting and typeset title into flash arrays."""
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
import numpy as np
import json
root=Path(__file__).resolve().parents[2]
im=Image.open(root/'art/solar_sky.png').convert('RGB').resize((320,240),Image.Resampling.LANCZOS)
a=np.asarray(im,dtype=np.uint16)
sky=(a[:,:,0]>>3)|((a[:,:,1]&248)<<3)|((a[:,:,2]&248)<<8)
title=Image.new('L',(280,48));d=ImageDraw.Draw(title);font=ImageFont.truetype('C:/Windows/Fonts/georgia.ttf',43)
name='HELION';width=sum(d.textlength(c,font=font) for c in name)+11*(len(name)-1);x=(280-width)/2
for c in name:d.text((x,-2),c,font=font,fill=255);x+=d.textlength(c,font=font)+11
arrays=[('sky',sky,'uint16_t'),('title',np.asarray(title),'uint8_t')]
with (root/'helion/assets.c').open('w',encoding='utf-8') as c,(root/'helion/assets.h').open('w',encoding='utf-8') as h:
    c.write('/* Generated by tools/pack_assets.py */\n#include "assets.h"\n');h.write('#ifndef HELION_ASSETS_H\n#define HELION_ASSETS_H\n#include <stdint.h>\n')
    for name,a,kind in arrays:
        h.write(f'extern const {kind} art_{name}[{a.size}];\n');c.write(f'const {kind} art_{name}[{a.size}] __attribute__((aligned(4))) = {{\n')
        v=a.flatten()
        for i in range(0,len(v),32):c.write(','.join(map(str,v[i:i+32]))+',\n')
        c.write('};\n')
    h.write('#endif\n')
(root/'art/manifest.json').write_text(json.dumps({name:int(a.nbytes) for name,a,_ in arrays},indent=2)+'\n')
