/* assets.h -- generated by tools/pack_assets.py. Do not edit. */
#ifndef SLEEPER_ASSETS_H
#define SLEEPER_ASSETS_H
#include <stdint.h>
#define SKY_W 320
#define SKY_H 240
#define SKY_COLORS 256

extern const uint8_t sky_night_idx[SKY_W * SKY_H];
extern const uint8_t sky_night_pal[SKY_COLORS * 3];
extern const uint8_t sky_dawn_idx[SKY_W * SKY_H];
extern const uint8_t sky_dawn_pal[SKY_COLORS * 3];
#endif
