"""Resize production plates and pack the Pico's RGB555-with-gap pixel format.

This is asset compilation, not an alternate renderer. Sources remain in art/.
No external files are read by the firmware or desktop player at runtime.
"""
from pathlib import Path
import json
import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'pelagic'

def rgb555(image):
    a = np.asarray(image.convert('RGB'), dtype=np.uint16)
    return ((a[...,0] >> 3) | ((a[...,1] & 248) << 3) | ((a[...,2] & 248) << 8))

arrays = []
for name in ('reef', 'abyss', 'surface'):
    im = Image.open(ROOT/'art'/f'{name}_source.png').resize((480,320), Image.Resampling.LANCZOS)
    arrays.append((name, rgb555(im), 'uint16_t'))
ray = Image.open(ROOT/'art'/'ray_source.png').convert('RGBA').resize((384,256), Image.Resampling.LANCZOS)
arrays.append(('ray_color', rgb555(ray), 'uint16_t'))
arrays.append(('ray_alpha', np.asarray(ray.getchannel('A')), 'uint8_t'))
title = Image.new('L', (280,48))
font_path = Path('C:/Windows/Fonts/georgia.ttf')
if not font_path.exists():
    raise SystemExit('Install Georgia or supply an equivalent serif font in pack_assets.py; checked-in assets.c needs no font to build.')
font = ImageFont.truetype(str(font_path), 43)
draw = ImageDraw.Draw(title)
letters = 'PELAGIC'
width = sum(draw.textlength(c,font=font) for c in letters) + 7*(len(letters)-1)
x = (280-width)/2
for letter in letters:
    draw.text((x,-2), letter, fill=255, font=font)
    x += draw.textlength(letter,font=font)+7
arrays.append(('title_alpha', np.asarray(title), 'uint8_t'))

with (OUT/'assets.h').open('w') as h, (OUT/'assets.c').open('w') as c:
    h.write('#ifndef PELAGIC_ASSETS_H\n#define PELAGIC_ASSETS_H\n#include <stdint.h>\n')
    c.write('/* Generated by tools/pack_assets.py. Read-only flash, no boot-time expansion. */\n#include "assets.h"\n')
    for name,a,kind in arrays:
        values=a.reshape(-1)
        h.write(f'extern const {kind} art_{name}[{values.size}];\n')
        c.write(f'const {kind} art_{name}[{values.size}] = {{\n')
        for start in range(0, values.size, 32):
            c.write(','.join(str(v) for v in values[start:start+32])+',\n')
        c.write('};\n')
    h.write('#endif\n')
manifest={name: {'shape':list(a.shape),'bytes':int(a.nbytes)} for name,a,_ in arrays}
manifest['total_bytes']=sum(a.nbytes for _,a,_ in arrays)
(ROOT/'art'/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps(manifest,indent=2))
