"""Generate synth_tables.h.

    python tools/gen_synth_tables.py > synth_tables.h

Everything the synth needs that would otherwise require a pow(), a sin() or a
division at runtime. The synth must be bit-identical on x86 and on Cortex-M33
(synth.h), and the cheapest way to guarantee that is for neither target to do
any floating point at all -- so it happens here, once, in double precision, and
ships as integers.

Run this only if the sample rate or the note range changes. It is not part of
the build: a generated file that regenerates on every build is a generated file
that can silently change what the demo sounds like.
"""

import math

RATE = 22050
NOTE_LO, NOTE_HI = 12, 107


def hz(n):
    return 440.0 * 2.0 ** ((n - 69) / 12.0)


def main():
    out = []
    a = out.append

    a("/* GENERATED by tools/gen_synth_tables.py -- do not hand-edit. */")
    a("#ifndef HYST_SYNTH_TABLES_H")
    a("#define HYST_SYNTH_TABLES_H")
    a("#include <stdint.h>")
    a("")
    a(f"#define SYNTH_NOTE_LO {NOTE_LO}")
    a(f"#define SYNTH_NOTE_HI {NOTE_HI}")
    a("")
    a(f"/* Phase increment per sample at {RATE} Hz for MIDI {NOTE_LO}..{NOTE_HI},")
    a(" * so a uint32 phase accumulator wraps once per cycle. */")
    inc = [int(round(hz(n) * (2 ** 32) / RATE)) for n in range(NOTE_LO, NOTE_HI + 1)]
    a(f"static const uint32_t g_note_inc[{len(inc)}] = {{")
    for i in range(0, len(inc), 6):
        a("    " + " ".join("%10du," % v for v in inc[i:i + 6]))
    a("};")
    a("")
    a("/* Rotation coefficients cos(w) and sin(w) in Q30, w = 2*pi*f/fs, per note.")
    a(" *")
    a(" * These exist because the resonators in synth.c are QUADRATURE oscillators,")
    a(" * and a quadrature oscillator has to be handed its angle as a sin/cos pair.")
    a(" * Deriving that pair at runtime from a shared sine table does not work: a")
    a(" * 1024-entry table resolves an angle to 64/65536 of a cycle, and at D2 the")
    a(" * whole angle is only 218 of those units, so truncation moved the pitch by a")
    a(" * semitone and a half. Interpolating helps the sine and not the cosine --")
    a(" * cos(w) = 1 - w^2/2 near zero, so a 1e-6 error in cos is a 0.3% error in w.")
    a(" * Ninety-six exact pairs is 768 bytes and the problem stops existing; the")
    a(" * measured tuning error across the range is now under one cent.")
    a(" *")
    a(" * The two-pole form y[n] = 2r*cos(w)*y[n-1] - r^2*y[n-2] has the same defect")
    a(" * structurally -- it can only learn its pitch through a cosine -- which is")
    a(" * why the resonators are rotations instead, at twice the multiplies. */")
    for name, fn in (("cos", math.cos), ("sin", math.sin)):
        vals = [int(round(fn(2 * math.pi * hz(n) / RATE) * (2 ** 30)))
                for n in range(NOTE_LO, NOTE_HI + 1)]
        assert max(abs(v) for v in vals) < 2 ** 31, "Q30 overflow"
        a(f"static const int32_t g_note_{name}[{len(vals)}] = {{")
        for i in range(0, len(vals), 5):
            a("    " + " ".join("%11d," % v for v in vals[i:i + 5]))
        a("};")
    a("")
    a("/* Quarter sine, Q15, for the LFOs and the thud oscillator -- neither of which")
    a(" * cares about a tenth of a cent. 257 entries so the mirror can read index 256")
    a(" * without reading the element it is about to write, which is the exact")
    a(" * self-reference bug field.c hit building its own table. */")
    q = [int(round(32767 * math.sin(math.pi / 2 * i / 256.0))) for i in range(257)]
    a("static const int16_t g_quarter[257] = {")
    for i in range(0, 257, 8):
        a("    " + " ".join("%6d," % v for v in q[i:i + 8]))
    a("};")
    a("")
    a("#endif")

    print("\n".join(out))


if __name__ == "__main__":
    main()
