"""Pack the 1-bit art into a C header.

    python tools/pack_assets.py > stencil.h

The two PNGs in assets/ are already 1-bit and already drawn on a 320x240 canvas
that matches the field exactly, so there is no scaling and no thresholding
decision to get wrong -- this only crops each image to its ink and emits the
bits, plus the offset the crop came from, so placing a stencil at its recorded
(ox, oy) reproduces the artwork pixel for pixel.

Cropping is for flash: the endcard is 9600 bytes uncropped and 7840 cropped, the
wordmark 4800 and 2432. Not decisive on its own, but free.

Bit order is MSB-first within each byte, which is what field_inject_stencil
expects (field.c).
"""

import sys

from PIL import Image

ASSETS = [
    ("wordmark", "../assets/hysteresis_wordmark.png"),
    ("endcard", "../assets/latent_endcard.png"),
]


def pack(path):
    im = Image.open(path).convert("L")
    w, h = im.size
    px = im.load()
    ink = [[px[x, y] > 127 for x in range(w)] for y in range(h)]

    xs = [x for y in range(h) for x in range(w) if ink[y][x]]
    ys = [y for y in range(h) for x in range(w) if ink[y][x]]
    if not xs:
        raise SystemExit(f"{path}: no ink")
    x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
    cw, ch = x1 - x0 + 1, y1 - y0 + 1
    stride = (cw + 7) >> 3

    data = bytearray(stride * ch)
    for j in range(ch):
        for i in range(cw):
            if ink[y0 + j][x0 + i]:
                data[j * stride + (i >> 3)] |= 0x80 >> (i & 7)
    return data, cw, ch, x0, y0, stride, (w, h)


def main():
    out = []
    a = out.append
    a("/* GENERATED by tools/pack_assets.py -- do not hand-edit. */")
    a("#ifndef HYST_STENCIL_H")
    a("#define HYST_STENCIL_H")
    a("#include <stdint.h>")
    a("")
    a("/* 1-bit art, MSB-first, cropped to its ink. Place a stencil at its own")
    a(" * (OX, OY) and it lands exactly where it was drawn on the 320x240 canvas. */")
    a("")

    for name, path in ASSETS:
        data, cw, ch, ox, oy, stride, orig = pack(path)
        up = name.upper()
        a(f"/* {path} -- {orig[0]}x{orig[1]} canvas, ink {cw}x{ch} at ({ox},{oy}) */")
        a(f"#define {up}_W {cw}")
        a(f"#define {up}_H {ch}")
        a(f"#define {up}_OX {ox}")
        a(f"#define {up}_OY {oy}")
        a(f"static const uint8_t g_{name}_bits[{len(data)}] = {{")
        for i in range(0, len(data), 16):
            a("    " + " ".join("0x%02X," % b for b in data[i:i + 16]))
        a("};")
        a("")
        print(f"{name}: {cw}x{ch} at ({ox},{oy}), {len(data)} bytes",
              file=sys.stderr)

    a("#endif")
    print("\n".join(out))


if __name__ == "__main__":
    main()
