/* GENERATED by tools/pack_assets.py — do not edit by hand. */
#ifndef SUSTAIN_ASSETS_H
#define SUSTAIN_ASSETS_H
#include <stdint.h>

/* surface_cold: rgb565 128x128 32768 bytes */
extern const uint8_t  asset_surface_cold_data[];
extern const uint8_t  asset_surface_cold_end[];
#define ASSET_SURFACE_COLD_W 128
#define ASSET_SURFACE_COLD_H 128
#define ASSET_SURFACE_COLD_SIZE 32768

/* surface_hot: rgb565 128x128 32768 bytes */
extern const uint8_t  asset_surface_hot_data[];
extern const uint8_t  asset_surface_hot_end[];
#define ASSET_SURFACE_HOT_W 128
#define ASSET_SURFACE_HOT_H 128
#define ASSET_SURFACE_HOT_SIZE 32768

/* relief_soft: gray8 256x256 65536 bytes */
extern const uint8_t  asset_relief_soft_data[];
extern const uint8_t  asset_relief_soft_end[];
#define ASSET_RELIEF_SOFT_W 256
#define ASSET_RELIEF_SOFT_H 256
#define ASSET_RELIEF_SOFT_SIZE 65536

/* relief_hard: gray8 256x256 65536 bytes */
extern const uint8_t  asset_relief_hard_data[];
extern const uint8_t  asset_relief_hard_end[];
#define ASSET_RELIEF_HARD_W 256
#define ASSET_RELIEF_HARD_H 256
#define ASSET_RELIEF_HARD_SIZE 65536

/* sky_pano: rgb565 1024x128 262144 bytes */
extern const uint8_t  asset_sky_pano_data[];
extern const uint8_t  asset_sky_pano_end[];
#define ASSET_SKY_PANO_W 1024
#define ASSET_SKY_PANO_H 128
#define ASSET_SKY_PANO_SIZE 262144

/* matcap_cold: rgb565 128x128 32768 bytes */
extern const uint8_t  asset_matcap_cold_data[];
extern const uint8_t  asset_matcap_cold_end[];
#define ASSET_MATCAP_COLD_W 128
#define ASSET_MATCAP_COLD_H 128
#define ASSET_MATCAP_COLD_SIZE 32768

/* matcap_warm: rgb565 128x128 32768 bytes */
extern const uint8_t  asset_matcap_warm_data[];
extern const uint8_t  asset_matcap_warm_end[];
#define ASSET_MATCAP_WARM_W 128
#define ASSET_MATCAP_WARM_H 128
#define ASSET_MATCAP_WARM_SIZE 32768

/* sustain_logo: rgb565 236x59 27848 bytes */
extern const uint8_t  asset_sustain_logo_data[];
extern const uint8_t  asset_sustain_logo_end[];
#define ASSET_SUSTAIN_LOGO_W 236
#define ASSET_SUSTAIN_LOGO_H 59
#define ASSET_SUSTAIN_LOGO_SIZE 27848

/* latent_logo: rgb565 256x48 24576 bytes */
extern const uint8_t  asset_latent_logo_data[];
extern const uint8_t  asset_latent_logo_end[];
#define ASSET_LATENT_LOGO_W 256
#define ASSET_LATENT_LOGO_H 48
#define ASSET_LATENT_LOGO_SIZE 24576

/* wall_cold: rgb565 128x128 32768 bytes */
extern const uint8_t  asset_wall_cold_data[];
extern const uint8_t  asset_wall_cold_end[];
#define ASSET_WALL_COLD_W 128
#define ASSET_WALL_COLD_H 128
#define ASSET_WALL_COLD_SIZE 32768

/* wall_hot: rgb565 128x128 32768 bytes */
extern const uint8_t  asset_wall_hot_data[];
extern const uint8_t  asset_wall_hot_end[];
#define ASSET_WALL_HOT_W 128
#define ASSET_WALL_HOT_H 128
#define ASSET_WALL_HOT_SIZE 32768

#endif
