#!/usr/bin/env python3
"""COLOSSUS converter v2: fixed palettes, explicit resampling, DAC-exact previews.
Run from any directory. Python 3 + Pillow; no stochastic quantizer or runtime heap.
"""
from pathlib import Path
from PIL import Image, __version__ as pillow_version
import hashlib,json,argparse
ROOT=Path(__file__).resolve().parents[1]; A=ROOT/'assets'; SRC=A/'source'
def sha(data):return hashlib.sha256(data).hexdigest()
def ramp(a,b,n):return [tuple((a[c]*(n-1-i)+b[c]*i)//(n-1)&248 for c in range(3)) for i in range(n)]
def palette(kind):
    if kind=='wordmark':return [(16,24,32)]+ramp((40,32,24),(184,152,104),15)
    if kind=='bronze':return [(30+i*154//255&248,31+i*121//255&248,32+i*72//255&248) for i in range(256)]
    if kind=='stone':return ramp((24,28,32),(104,96,80),256)
    if kind=='warm':return ramp((16,24,32),(224,104,32),128)+ramp((32,32,32),(216,200,168),128)
    if kind=='ember':return [(0,0,0)]+ramp((48,24,8),(248,208,128),15)
    if kind=='end':return [(0,0,0)]+ramp((48,48,48),(184,168,144),15)
    if kind=='sky':
        return [tuple(min(248,v)&248 for v in (16+i*5+j*2,24+i*5+j*3,40+i*6+j*2)) for j in range(16) for i in range(16)]
    return ramp((16,24,32),(216,224,224),224)+ramp((40,32,24),(112,96,72),32)
def dac(c):r,g,b=c;return (r>>3)|((g&248)<<3)|((b&248)<<8)
def array(f,typ,name,values):
    f.write('_Alignas(4) const '+typ+' '+name+'['+str(len(values))+'] = {\n')
    for i in range(0,len(values),24):f.write(','.join(map(str,values[i:i+24]))+',\n')
    f.write('};\n')
def paired_palette(dusk_path,dawn_path,size):
    """Fixed deterministic six-channel median partition, no random seed/state.
    Shared indices encode BOTH paintings so only palettes change at runtime.
    """
    dusk=Image.open(dusk_path).convert('RGB').resize(size,Image.Resampling.LANCZOS)
    dawn=Image.open(dawn_path).convert('RGB').resize(size,Image.Resampling.LANCZOS)
    pixels=[tuple(v&248 for v in a+b) for a,b in zip(dusk.getdata(),dawn.getdata())]
    hist={}
    for p in pixels:hist[p]=hist.get(p,0)+1
    groups=[sorted(hist)]
    while len(groups)<256:
        choices=[]
        for i,g in enumerate(groups):
            if len(g)<2:continue
            ranges=[max(p[k] for p in g)-min(p[k] for p in g) for k in range(6)]
            axis=max(range(6),key=lambda k:ranges[k]);choices.append((ranges[axis]*sum(hist[p] for p in g),i,axis))
        if not choices:break
        _,i,axis=max(choices);g=sorted(groups.pop(i),key=lambda p:(p[axis],p));half=sum(hist[p] for p in g)/2;acc=0;cut=1
        for j,pixel in enumerate(g[:-1]):
            acc+=hist[pixel];cut=j+1
            if acc>=half:break
        groups.extend([g[:cut],g[cut:]])
    lookup={};pa=[];pb=[]
    for i,g in enumerate(groups):
        count=sum(hist[p] for p in g);mean=tuple((sum(p[k]*hist[p] for p in g)//count)&248 for k in range(6))
        pa.append(mean[:3]);pb.append(mean[3:])
        for pixel in g:lookup[pixel]=i
    while len(pa)<256:pa.append(pa[-1]);pb.append(pb[-1])
    return [lookup[p] for p in pixels],pa,pb

def convert(check=False):
    manifest={'converter_version':2,'pillow_version':pillow_version,'seed':0,'quantizer':'nearest fixed palette RGB squared distance; deterministic first-index ties','dac':'r0:4 g6:10 b11:15; bit5 zero','assets':[]}
    pairs={}
    for kind,size in [('sky',(256,64)),('matcap',(64,64))]:
        d=SRC/('dusk-sky-master.png' if kind=='sky' else 'dusk-matcap-v3-master.png')
        a=SRC/('dawn-'+kind+'-master.png')
        pairs[kind]=paired_palette(d,a,size)
    shared={};outputs={};decl=['#ifndef COLOSSUS_PAINTED_ASSETS_H','#define COLOSSUS_PAINTED_ASSETS_H','#include <stdint.h>']
    import io
    c=io.StringIO();c.write('/* Generated by tools/convert_assets.py. Flash, no decompression. */\n#include "painted_assets.h"\n')
    for name,size,bits,kind in [('wordmark',(320,64),4,'wordmark'),('dusk_matcap',(64,64),8,'matcap'),('dusk_sky',(256,64),8,'sky'),
        ('bronze_wear',(64,64),8,'bronze'),('stone',(64,64),8,'stone'),
        ('dawn_sky',(256,64),8,'sky'),('dawn_matcap',(64,64),8,'matcap'),
        ('warm_environment',(64,64),8,'warm'),('furnace',(64,32),8,'warm'),
        ('ember_stamps',(16,64),4,'ember'),('end_inscription',(320,32),4,'end')]:
        filename={'wordmark':'wordmark-painted-master.png','dusk_matcap':'dusk-matcap-v3-master.png','warm_environment':'warm-environment-v2-master.png'}.get(name,name.replace('_','-')+'-master.png')
        path=SRC/filename;source=path.read_bytes();im=Image.open(path).convert('RGB')
        # Wordmark master has generous vertical margins; map its painted bounding
        # box to the drawn forms before applying the exact binary drawing mask.
        crop=None
        if name=='wordmark':
            # Tool master 2164x727: detect bronze, independent of output dimensions.
            coords=[(x,y) for y in range(im.height) for x in range(im.width) if (lambda p:p[0]>p[2]*1.15 and p[0]>45)(im.getpixel((x,y)))]
            crop=(min(x for x,y in coords),min(y for x,y in coords),max(x for x,y in coords)+1,max(y for x,y in coords)+1)
            painted=im.crop(crop).resize((299,47),Image.Resampling.LANCZOS)
            im=Image.new('RGB',size,(16,24,32));im.paste(painted,(8,9))
        else:im=im.resize(size,Image.Resampling.LANCZOS)
        pal=palette(kind);maskdata=list(Image.open(SRC/'wordmark-drawn.png').convert('RGB').getdata()) if name=='wordmark' else None
        indices=[];cache={}
        for i,p in enumerate(im.getdata()):
            if maskdata is not None and maskdata[i]==(16,24,32):indices.append(0);continue
            if p not in cache:
                start=1 if name=='wordmark' else 0
                cache[p]=min(range(start,len(pal)),key=lambda j:sum((p[k]-pal[j][k])**2 for k in range(3)))
            indices.append(cache[p])
        mapping=None
        if name in ('dusk_sky','dawn_sky','dusk_matcap','dawn_matcap'):
            kind=name.split('_')[1];indices,dp,ap=pairs[kind];pal=ap if name.startswith('dawn') else dp
            mapping={'shared_indices':'dusk/dawn '+kind,'method':'deterministic paired RGB median partition, weighted means, floor to 5-bit DAC','dawn_source_sha256':sha((SRC/('dawn-'+kind+'-master.png')).read_bytes()),'dusk_source_sha256':sha((SRC/('dusk-sky-master.png' if kind=='sky' else 'dusk-matcap-v3-master.png')).read_bytes())}
        if name=='ember_stamps':
            # Preserve painted shape, normalize per-cell luminance for runtime
            # brightness classes, and use index 0 for the black surround.
            rgb=list(im.getdata());indices=[]
            for cell in range(4):
                lum=[max(p) for p in rgb[cell*256:(cell+1)*256]];peak=max(lum) or 1
                indices.extend(min(15,v*15//peak) for v in lum)
        shared[name]=(indices,pal)
        packed=bytes(indices) if bits==8 else bytes((indices[i]<<4)|indices[i+1] for i in range(0,len(indices),2))
        unpacked=list(packed) if bits==8 else [j for v in packed for j in (v>>4,v&15)]
        assert unpacked==indices,'packing roundtrip failed'
        preview=Image.new('RGB',size);preview.putdata([pal[j] for j in unpacked])
        # Roundtrip DAC colors too; DAC-expand with <<3, matching palette steps.
        assert all(((dac(p)&31)*8,((dac(p)>>6)&31)*8,((dac(p)>>11)&31)*8)==p for p in pal)
        buf=io.BytesIO();preview.save(buf,format='PNG');outputs[A/(name+'-quantized.png')]=buf.getvalue()
        array(c,'uint8_t',name+'_pixels',packed);array(c,'uint16_t',name+'_palette',[dac(p) for p in pal])
        decl.extend([f'extern const uint8_t {name}_pixels[{len(packed)}];',f'extern const uint16_t {name}_palette[{len(pal)}];'])
        manifest['assets'].append(dict(name=name,width=size[0],height=size[1],bits=bits,source=str(path.relative_to(ROOT)),source_sha256=sha(source),crop=crop,resize='LANCZOS',drawn_mask_sha256=sha((SRC/'wordmark-drawn.png').read_bytes()) if maskdata else None,transparency_index=0 if bits==4 else None,palette=[('#%02x%02x%02x'%p) for p in pal],pixel_bytes=len(packed),palette_bytes=len(pal)*2,pixel_sha256=sha(packed),preview_sha256=sha(buf.getvalue()),nibble_order='high first' if bits==4 else None,palette_mapping=mapping,roundtrip=True))
    engine=io.StringIO();engine.write('#include "engine_assets.h"\n')
    for name,size,bits,mode in [('inscription_atlas',(128,64),1,'1'),('diagnostic_tile',(64,64),8,'L')]:
        path=SRC/(name.replace('_','-')+'.png');raw=path.read_bytes();im=Image.open(path).convert(mode)
        assert im.size==size
        packed=im.tobytes();decoded=Image.frombytes(mode,size,packed)
        assert decoded.tobytes()==im.tobytes()
        array(engine,'uint8_t',name,packed)
        manifest['assets'].append(dict(name=name,width=size[0],height=size[1],bits=bits,source=str(path.relative_to(ROOT)),source_sha256=sha(raw),resize='none',transparency_index=0 if bits==1 else None,palette=['#000000','#ffffff'] if bits==1 else 'SRAM material shade intensity lookup',pixel_bytes=len(packed),palette_bytes=0,pixel_sha256=sha(packed),bit_order='MSB first' if bits==1 else None,roundtrip=True))
    outputs[A/'engine_assets.c']=engine.getvalue().encode()
    outputs[A/'engine_assets.h']=b'#include <stdint.h>\nextern const uint8_t inscription_atlas[1024], diagnostic_tile[4096];\n'
    decl.append('#endif');outputs[A/'painted_assets.h']=('\n'.join(decl)+'\n').encode();outputs[A/'painted_assets.c']=c.getvalue().encode()
    manifest['flash_bytes']=sum(a['pixel_bytes']+a['palette_bytes'] for a in manifest['assets'])
    assert manifest['flash_bytes']<=128*1024,'asset allowance exceeded'
    outputs[A/'manifest.json']=(json.dumps(manifest,indent=2)+'\n').encode()
    for path,data in outputs.items():
        if check:
            if not path.exists() or path.read_bytes()!=data:raise SystemExit('not reproducible: '+str(path))
        else:path.write_bytes(data)
    print(('Verified' if check else 'Wrote')+f" {len(manifest['assets'])} assets: {manifest['flash_bytes']} flash bytes; packing and DAC roundtrips pass")
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');convert(p.parse_args().check)
