/* GENERATED by tools/pack_assets.py — do not edit by hand. */
#ifndef THEDEMO_ASSETS_H
#define THEDEMO_ASSETS_H
#include <stdint.h>

/* title_bg: 8bpp 320x240 76800 bytes + 512 B palette */
extern const uint8_t  asset_title_bg_data[];
extern const uint8_t  asset_title_bg_end[];
#define ASSET_TITLE_BG_W 320
#define ASSET_TITLE_BG_H 240
#define ASSET_TITLE_BG_SIZE 76800
extern const uint16_t asset_title_bg_pal[256];

/* roto: rgb565 256x256 131072 bytes */
extern const uint8_t  asset_roto_data[];
extern const uint8_t  asset_roto_end[];
#define ASSET_ROTO_W 256
#define ASSET_ROTO_H 256
#define ASSET_ROTO_SIZE 131072

/* ground: rgb565 256x256 131072 bytes */
extern const uint8_t  asset_ground_data[];
extern const uint8_t  asset_ground_end[];
#define ASSET_GROUND_W 256
#define ASSET_GROUND_H 256
#define ASSET_GROUND_SIZE 131072

/* envmap: rgb565 256x256 131072 bytes */
extern const uint8_t  asset_envmap_data[];
extern const uint8_t  asset_envmap_end[];
#define ASSET_ENVMAP_W 256
#define ASSET_ENVMAP_H 256
#define ASSET_ENVMAP_SIZE 131072

/* sky: rgb565 1024x128 262144 bytes */
extern const uint8_t  asset_sky_data[];
extern const uint8_t  asset_sky_end[];
#define ASSET_SKY_W 1024
#define ASSET_SKY_H 128
#define ASSET_SKY_SIZE 262144

/* title_logo: rgb565 320x80 51200 bytes */
extern const uint8_t  asset_title_logo_data[];
extern const uint8_t  asset_title_logo_end[];
#define ASSET_TITLE_LOGO_W 320
#define ASSET_TITLE_LOGO_H 80
#define ASSET_TITLE_LOGO_SIZE 51200

/* tunnel: rgb565 256x256 131072 bytes */
extern const uint8_t  asset_tunnel_data[];
extern const uint8_t  asset_tunnel_end[];
#define ASSET_TUNNEL_W 256
#define ASSET_TUNNEL_H 256
#define ASSET_TUNNEL_SIZE 131072

/* latent_logo: rgb565 256x48 24576 bytes */
extern const uint8_t  asset_latent_logo_data[];
extern const uint8_t  asset_latent_logo_end[];
#define ASSET_LATENT_LOGO_W 256
#define ASSET_LATENT_LOGO_H 48
#define ASSET_LATENT_LOGO_SIZE 24576

/* conduit: rgb565 128x128 32768 bytes */
extern const uint8_t  asset_conduit_data[];
extern const uint8_t  asset_conduit_end[];
#define ASSET_CONDUIT_W 128
#define ASSET_CONDUIT_H 128
#define ASSET_CONDUIT_SIZE 32768

/* conduit_bump: gray8 256x256 65536 bytes */
extern const uint8_t  asset_conduit_bump_data[];
extern const uint8_t  asset_conduit_bump_end[];
#define ASSET_CONDUIT_BUMP_W 256
#define ASSET_CONDUIT_BUMP_H 256
#define ASSET_CONDUIT_BUMP_SIZE 65536

/* envmap2: rgb565 128x128 32768 bytes */
extern const uint8_t  asset_envmap2_data[];
extern const uint8_t  asset_envmap2_end[];
#define ASSET_ENVMAP2_W 128
#define ASSET_ENVMAP2_H 128
#define ASSET_ENVMAP2_SIZE 32768

/* envmap3: rgb565 128x128 32768 bytes */
extern const uint8_t  asset_envmap3_data[];
extern const uint8_t  asset_envmap3_end[];
#define ASSET_ENVMAP3_W 128
#define ASSET_ENVMAP3_H 128
#define ASSET_ENVMAP3_SIZE 32768

#endif
