/* GENERATED by tools/pack_assets.py — do not edit by hand. */
#ifndef THEDEMO_ASSETS_H
#define THEDEMO_ASSETS_H
#include <stdint.h>

/* title_bg: 8bpp 320x240 76800 bytes + 512 B palette */
extern const uint8_t  asset_title_bg_data[];
extern const uint8_t  asset_title_bg_end[];
#define ASSET_TITLE_BG_W 320
#define ASSET_TITLE_BG_H 240
#define ASSET_TITLE_BG_SIZE 76800
extern const uint16_t asset_title_bg_pal[256];

/* envmap: rgb565 256x256 131072 bytes */
extern const uint8_t  asset_envmap_data[];
extern const uint8_t  asset_envmap_end[];
#define ASSET_ENVMAP_W 256
#define ASSET_ENVMAP_H 256
#define ASSET_ENVMAP_SIZE 131072

/* ground: rgb565 256x256 131072 bytes */
extern const uint8_t  asset_ground_data[];
extern const uint8_t  asset_ground_end[];
#define ASSET_GROUND_W 256
#define ASSET_GROUND_H 256
#define ASSET_GROUND_SIZE 131072

/* roto: rgb565 256x256 131072 bytes */
extern const uint8_t  asset_roto_data[];
extern const uint8_t  asset_roto_end[];
#define ASSET_ROTO_W 256
#define ASSET_ROTO_H 256
#define ASSET_ROTO_SIZE 131072

/* sky: rgb565 512x128 131072 bytes */
extern const uint8_t  asset_sky_data[];
extern const uint8_t  asset_sky_end[];
#define ASSET_SKY_W 512
#define ASSET_SKY_H 128
#define ASSET_SKY_SIZE 131072

#endif
