#!/usr/bin/env python3
"""
pack_assets.py — converts PNG assets in ../assets/ into raw binary formats
for RP2350 engine, emitting assets.S + assets.h in ../assets/_packed/.
"""

import os
import sys
import struct
from pathlib import Path
from PIL import Image, ImageOps

HERE         = Path(__file__).resolve().parent
ASSETS_DIR   = HERE.parent / "assets"
OUT_DIR      = ASSETS_DIR / "_packed"

# (name, source_png, format, target_w, target_h, dither)
ASSETS = [
    ("surface_cold", "surface_cold.png", "rgb565", 128, 128, False),
    ("surface_hot",  "surface_hot.png",  "rgb565", 128, 128, False),
    ("relief_soft",  "relief_soft.png",  "gray8",  256, 256, False),
    ("relief_hard",  "relief_hard.png",  "gray8",  256, 256, False),
    ("sky_pano",     "sky_pano.png",     "rgb565", 1024, 128, False),
    ("matcap_cold",  "matcap_cold.png",  "rgb565", 128, 128, False),
    ("matcap_warm",  "matcap_warm.png",  "rgb565", 128, 128, False),
    ("sustain_logo", "sustain_logo.png", "rgb565", 236, 59,  False),
    ("latent_logo",  "latent_logo.png",  "rgb565", 256, 48,  False),
    ("wall_cold",    "wall_cold.png",    "rgb565", 128, 128, False),
    ("wall_hot",     "wall_hot.png",     "rgb565", 128, 128, False),
]


def rgb_to_565(r, g, b):
    return ((b & 0xF8) << 8) | ((g & 0xF8) << 3) | (r >> 3)


def pack_rgb565(img, out_bin):
    img = img.convert("RGB")
    px = img.load()
    w, h = img.size
    buf = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            buf += struct.pack("<H", rgb_to_565(r, g, b))
    out_bin.write_bytes(bytes(buf))


def pack_gray8(img, out_bin):
    img = img.convert("L")
    out_bin.write_bytes(img.tobytes())


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    manifest = []
    total = 0

    for entry in ASSETS:
        name, src, fmt, w, h, dither = entry
        out_bin = OUT_DIR / f"{name}.bin"

        png = ASSETS_DIR / src
        if not png.exists():
            print(f"  SKIP {name}: {src} missing")
            continue
            
        img = Image.open(png).convert("RGB")
        
        # Crop wordmark logos if needed before strip resize
        if name.endswith("_logo"):
            gray = img.convert("L")
            bbox = gray.point(lambda v: 255 if v > 24 else 0).getbbox()
            if bbox:
                m = 8
                bbox = (max(0, bbox[0]-m), max(0, bbox[1]-m),
                        min(img.width, bbox[2]+m), min(img.height, bbox[3]+m))
                img = img.crop(bbox)
                
        img = img.resize((w, h), Image.LANCZOS)

        if fmt == "rgb565":
            pack_rgb565(img, out_bin)
        elif fmt == "gray8":
            pack_gray8(img, out_bin)
        else:
            print(f"  ERR  {name}: unknown format {fmt}")
            continue

        size = out_bin.stat().st_size
        total += size
        manifest.append((name, fmt, w, h, size))
        print(f"  PACK {name:15s} {fmt:6s} {w}x{h:<4d} -> {size:6d} B")

    print(f"\nTotal packed: {total} bytes ({total/1024:.1f} KB)")

    write_assets_s(manifest)
    write_assets_h(manifest)
    print(f"  wrote {OUT_DIR/'assets.S'}")
    print(f"  wrote {OUT_DIR/'assets.h'}")


def write_assets_s(manifest):
    lines = [
        "/* GENERATED by tools/pack_assets.py — do not edit by hand. */",
        "",
        '    .section .rodata.assets, "a"',
        "    .balign 4",
        "",
    ]
    for name, fmt, w, h, sz in manifest:
        lines += [
            f"    .global asset_{name}_data",
            f"asset_{name}_data:",
            f'    .incbin "{name}.bin"',
            f"    .global asset_{name}_end",
            f"asset_{name}_end:",
            "",
        ]
    (OUT_DIR / "assets.S").write_text("\n".join(lines), encoding="utf-8")


def write_assets_h(manifest):
    lines = [
        "/* GENERATED by tools/pack_assets.py — do not edit by hand. */",
        "#ifndef SUSTAIN_ASSETS_H",
        "#define SUSTAIN_ASSETS_H",
        "#include <stdint.h>",
        "",
    ]
    for name, fmt, w, h, sz in manifest:
        UN = name.upper()
        lines += [
            f"/* {name}: {fmt} {w}x{h} {sz} bytes */",
            f"extern const uint8_t  asset_{name}_data[];",
            f"extern const uint8_t  asset_{name}_end[];",
            f"#define ASSET_{UN}_W {w}",
            f"#define ASSET_{UN}_H {h}",
            f"#define ASSET_{UN}_SIZE {sz}",
            "",
        ]
    lines += ["#endif", ""]
    (OUT_DIR / "assets.h").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
