#!/usr/bin/env python3
"""Pack Phase's painted skies into flash: 8-bit indexed plates with a
256-entry palette each, plus a manifest recording exactly how.

PLANNING §9: the plate is expanded through a *per-frame tinted palette* into
the page, not DMA'd as RGB16 like HELION's sky -- one plate has to serve the
night, the first blue and the blue hour, and only a palette can do that. So
what goes into flash is the index plane and an 8-bit RGB palette; the tint
and the RGB555 quantisation both happen at expansion time, which is what
Phase's "dither after the final palette tint reaches RGB555" requires.

    python tools/pack_assets.py            # writes assets.c, assets.h, art/manifest.json

Deterministic: Pillow's median cut with a fixed input is reproducible, and
the manifest records the palette size, the dither and the SHA-256 of both
the source and the packed plane, so a regenerated asset that differs is
visible rather than silent.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent                       # sleeper/
ART = ROOT.parent / "art"

PLATES = [
    ("sky_night", "sky_night.png", "night plate: bars 0-103, tinted night -> first blue -> blue hour"),
    ("sky_dawn", "sky_dawn.png", "dawn plate: from the cut at 104:1, tint warming over 104-111"),
]
W, H, COLORS = 320, 240, 256


def sha(data):
    return hashlib.sha256(data).hexdigest()[:16]


def pack(path):
    src = Image.open(path).convert("RGB")
    if src.size != (W, H):
        src = src.resize((W, H), Image.LANCZOS)
    # Median cut with Floyd-Steinberg, the same method Phase proofed with.
    idx = src.quantize(colors=COLORS, method=Image.MEDIANCUT, dither=Image.Dither.FLOYDSTEINBERG)
    plane = idx.tobytes()
    pal = idx.getpalette()[: COLORS * 3]
    pal += [0] * (COLORS * 3 - len(pal))
    return plane, pal, src.tobytes()


def emit_array(out, name, data, per_line=32):
    out.append("const uint8_t %s[%d] = {" % (name, len(data)))
    for i in range(0, len(data), per_line):
        out.append("    " + ",".join(str(b) for b in data[i:i + per_line]) + ",")
    out.append("};")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--art", type=Path, default=ART)
    ap.add_argument("--out", type=Path, default=ROOT)
    args = ap.parse_args()

    manifest = {
        "tool": "sleeper/tools/pack_assets.py",
        "quantiser": "PIL Image.quantize MEDIANCUT + Floyd-Steinberg",
        "colors": COLORS,
        "size": [W, H],
        "note": "index plane + 8-bit RGB palette; the renderer tints the palette "
                "per frame and dithers 4x4 as it quantises to RGB555",
        "plates": {},
    }
    body = ["/* assets.c -- generated by tools/pack_assets.py. Do not edit.",
            " *",
            " * Phase's painted skies, 8-bit indexed with a 256-entry palette each, in",
            " * flash. render.c expands them through a tinted palette (sky_expand).",
            " */",
            '#include "assets.h"',
            ""]
    header = ["/* assets.h -- generated by tools/pack_assets.py. Do not edit. */",
              "#ifndef SLEEPER_ASSETS_H",
              "#define SLEEPER_ASSETS_H",
              "#include <stdint.h>",
              "#define SKY_W %d" % W,
              "#define SKY_H %d" % H,
              "#define SKY_COLORS %d" % COLORS,
              ""]
    for name, filename, note in PLATES:
        path = args.art / filename
        plane, pal, raw = pack(path)
        emit_array(body, "%s_idx" % name, plane)
        body.append("")
        emit_array(body, "%s_pal" % name, pal, per_line=24)
        body.append("")
        header.append("extern const uint8_t %s_idx[SKY_W * SKY_H];" % name)
        header.append("extern const uint8_t %s_pal[SKY_COLORS * 3];" % name)
        manifest["plates"][name] = {
            "source": filename,
            "note": note,
            "source_sha256_16": sha(open(path, "rb").read()),
            "rgb_sha256_16": sha(raw),
            "plane_sha256_16": sha(plane),
            "plane_bytes": len(plane),
            "palette_bytes": len(pal),
        }
    header.append("#endif")

    (args.out / "assets.c").write_text("\n".join(body) + "\n", encoding="utf-8")
    (args.out / "assets.h").write_text("\n".join(header) + "\n", encoding="utf-8")
    (args.art / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    total = sum(p["plane_bytes"] + p["palette_bytes"] for p in manifest["plates"].values())
    print("packed %d plates, %d bytes of flash" % (len(PLATES), total))
    for k, v in manifest["plates"].items():
        print("  %-10s plane %s  palette %d bytes" % (k, v["plane_sha256_16"], v["palette_bytes"]))


if __name__ == "__main__":
    main()
