/* GENERATED by tools/pack_assets.py — do not edit by hand. */
#ifndef THEDEMO_ASSETS_H
#define THEDEMO_ASSETS_H
#include <stdint.h>

/* title_bg: 8bpp 320x240 76800 bytes + 512 B palette */
extern const uint8_t  asset_title_bg_data[];
extern const uint8_t  asset_title_bg_end[];
#define ASSET_TITLE_BG_W 320
#define ASSET_TITLE_BG_H 240
#define ASSET_TITLE_BG_SIZE 76800
extern const uint16_t asset_title_bg_pal[256];

/* voxel_color: 8bpp 512x512 262144 bytes + 512 B palette */
extern const uint8_t  asset_voxel_color_data[];
extern const uint8_t  asset_voxel_color_end[];
#define ASSET_VOXEL_COLOR_W 512
#define ASSET_VOXEL_COLOR_H 512
#define ASSET_VOXEL_COLOR_SIZE 262144
extern const uint16_t asset_voxel_color_pal[256];

/* voxel_height: gray8 512x512 262144 bytes */
extern const uint8_t  asset_voxel_height_data[];
extern const uint8_t  asset_voxel_height_end[];
#define ASSET_VOXEL_HEIGHT_W 512
#define ASSET_VOXEL_HEIGHT_H 512
#define ASSET_VOXEL_HEIGHT_SIZE 262144

/* envmap: 8bpp 256x128 32768 bytes + 512 B palette */
extern const uint8_t  asset_envmap_data[];
extern const uint8_t  asset_envmap_end[];
#define ASSET_ENVMAP_W 256
#define ASSET_ENVMAP_H 128
#define ASSET_ENVMAP_SIZE 32768
extern const uint16_t asset_envmap_pal[256];

/* portrait_a: 8bpp 96x96 9216 bytes + 512 B palette */
extern const uint8_t  asset_portrait_a_data[];
extern const uint8_t  asset_portrait_a_end[];
#define ASSET_PORTRAIT_A_W 96
#define ASSET_PORTRAIT_A_H 96
#define ASSET_PORTRAIT_A_SIZE 9216
extern const uint16_t asset_portrait_a_pal[256];

/* portrait_b: 8bpp 96x96 9216 bytes + 512 B palette */
extern const uint8_t  asset_portrait_b_data[];
extern const uint8_t  asset_portrait_b_end[];
#define ASSET_PORTRAIT_B_W 96
#define ASSET_PORTRAIT_B_H 96
#define ASSET_PORTRAIT_B_SIZE 9216
extern const uint16_t asset_portrait_b_pal[256];

/* portrait_c: 8bpp 96x96 9216 bytes + 512 B palette */
extern const uint8_t  asset_portrait_c_data[];
extern const uint8_t  asset_portrait_c_end[];
#define ASSET_PORTRAIT_C_W 96
#define ASSET_PORTRAIT_C_H 96
#define ASSET_PORTRAIT_C_SIZE 9216
extern const uint16_t asset_portrait_c_pal[256];

/* logo_mask: 1bpp 160x120 2400 bytes */
extern const uint8_t  asset_logo_mask_data[];
extern const uint8_t  asset_logo_mask_end[];
#define ASSET_LOGO_MASK_W 160
#define ASSET_LOGO_MASK_H 120
#define ASSET_LOGO_MASK_SIZE 2400

/* tunnel_tex: 8bpp 256x256 65536 bytes + 512 B palette */
extern const uint8_t  asset_tunnel_tex_data[];
extern const uint8_t  asset_tunnel_tex_end[];
#define ASSET_TUNNEL_TEX_W 256
#define ASSET_TUNNEL_TEX_H 256
#define ASSET_TUNNEL_TEX_SIZE 65536
extern const uint16_t asset_tunnel_tex_pal[256];

/* greetz_bg: 8bpp 320x240 76800 bytes + 512 B palette */
extern const uint8_t  asset_greetz_bg_data[];
extern const uint8_t  asset_greetz_bg_end[];
#define ASSET_GREETZ_BG_W 320
#define ASSET_GREETZ_BG_H 240
#define ASSET_GREETZ_BG_SIZE 76800
extern const uint16_t asset_greetz_bg_pal[256];

/* endcard_mask: 1bpp 300x80 3040 bytes */
extern const uint8_t  asset_endcard_mask_data[];
extern const uint8_t  asset_endcard_mask_end[];
#define ASSET_ENDCARD_MASK_W 300
#define ASSET_ENDCARD_MASK_H 80
#define ASSET_ENDCARD_MASK_SIZE 3040

/* endcard_bg: 8bpp 320x240 76800 bytes + 512 B palette */
extern const uint8_t  asset_endcard_bg_data[];
extern const uint8_t  asset_endcard_bg_end[];
#define ASSET_ENDCARD_BG_W 320
#define ASSET_ENDCARD_BG_H 240
#define ASSET_ENDCARD_BG_SIZE 76800
extern const uint16_t asset_endcard_bg_pal[256];

#endif
